# Generated by Django 3.1.2 on 2023-10-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='restricted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
